spring.application.name=business-management-api-v2
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# update: Hibernate tự tạo/sửa bảng theo Entity. Chỉ để học, Phase 9 sẽ đổi sang Flyway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.web.error.include-message=always
server.web.error.include-binding-errors=always